### ISSUE TITLE
#6: Tapping a pin shows info about the place in the lower panel

### ISSUE THREAD

**Issue by segdeha** [the-collab-lab/tcl-pilot-2020-05#6]
AC:

1. Add an event handler to each map pin to handle the user tapping on them
2. Tapping on a pin should change the lower panel to show info about the place including title, thumbnail, description, and link to the place’s Wikipedia entry
3. Places always have a title
4. Places sometimes have a thumbnail
5. Places sometimes have a description
6. Sometimes, the description doesn’t start with a capital letter, but we’d like them always to display with a leading capital letter
7. Last thing should be a link to the Wikipedia page for the place
8. Tapping non-pin landmarks on the map should _not_ display the Google Maps default `InfoWindow`

**Comment by segdeha** [comment]
If you get stuck on how to create the link to the Wikipedia entry, you can look at [this line of code in whats-near.me](https://github.com/segdeha/whats-near.me/blob/master/src/Info.js#L15)

**Comment by jendevelops** [comment]
*AC:*

**1. Add an event handler to each map pin to handle the user tapping on them**
- [x] add currentPin app state (event target)
- [x] add displayInformation app state (at App.js level to pass down into both Footer and Map
- [x] event handler 
  -  click on pin => displayInformation = true, currentPin = clickedPin
  - click on map (no pin) => displayInformation = false, currentPin = null

**2. Tapping on a pin should change the lower panel to show info about the place including title, thumbnail, description, and link to the place’s Wikipedia entry**

- [x] create PlaceInformation component for display information (will live in Footer)
- [x] use App.js displayInformation state to render (see point 1)

**3. Places always have a title**
- [ ] use turnary operator to create default title (in PlaceInformation component)
   `<h1>Unnamed Landmark</h1>`

 **4. Places sometimes have a thumbnail**
- [ ] use turnary operator to create default thumbnail (in PlaceInformation component)
  `<img src="/img/default.png" alt="default image" />`
 5. Places sometimes have a description
- [ ] use turnary operator to create default description (in PlaceInformation component)
  `<p>Description: Unavailable</p>`

 **6. Sometimes, the description doesn’t start with a capital letter, but we’d like them always to display with a leading capital letter**
- [x] helper function to strip and capitalize first letter (helper function file in lib/)

 **7. Last thing should be a link to the Wikipedia page for the place**
- [x] use nearbyPlaces state to grab dictionary with information => pass into currentPin state(forces it to be on app level) for access in PlaceInformation component.

 **8. Tapping non-pin landmarks on the map should _not_ display the Google Maps default `InfoWindow`**
- see displayInformation state, need to null InfoWindow Google Map function to do that

**Comment by jendevelops** [comment]
*Plan 5/20/20*
- first make PinDescription component w/ dummy props in footer
- set up state at App level to pass down as props
