### ISSUE TITLE
Fetch places based on the user’s location

### ISSUE THREAD

**Issue by segdeha** [the-collab-lab/tcl-pilot-2020-05#7]
AC:

1. Use the user’s `lat`/`lng` as input to our call to the `nearby` API
2. Only call the API if we don’t already have a call in progress

**Comment by segdeha** [comment]
Don’t underestimate the complexity of this issue. There are several ways you _could_ solve that 2nd AC with various tradeoffs invovled.

**Comment by jendevelops** [comment]
### Psudo-code Notes from 5/28
- local state pendingPromise (bool) default False

*Map.js useEffect*
```
useEffect( () => {

if(!pendingPromise) {
  runAPIFetch().then(res => setNearbyPlaces(res), setPendingPromise(false))
}, [lat, lng] 
}
```
- within API promise function, need to setPendingPromise to True
- will have to test to see if React State updates quickly enough to prevent multiple api calls
- for testing console log from within runAPIFetch

@segdeha Does this seem plausible?
