### ISSUE TITLE
User can pan map manually to see places of interest

### ISSUE THREAD

**Issue by segdeha** [the-collab-lab/tcl-pilot-2020-05#8]
AC:

1. Add an icon + link to the top/left of the app in the `Header` (can use `public/img/center-on-me.png` for the icon)
2. When the map is centered on the user, the header icon should be grayed out
3. When the user manually pans the map, the header icon should be shown in color
4. When the user pans the map, an icon should be visible in the center of the map that’s distinct from the blue dot
5. When the user pans the map, pins should be fetched using the new map center
6. If the user has panned the map then taps the "center on me" icon, the map should return to being centered on the user
7. If the user has panned the map, the map should not center on the user again until the user manually indicates they want to be in that mode (by tapping the “center on me” icon in the `Header`)

**Comment by AshlingH** [comment]
What is left to do for this Issue:
 - [x] When the user pans the map, pins should be fetched using the new map center
- [x] If the user has panned the map, the map should not center on the user again until the user manually indicates they want to be in that mode (by tapping the “center on me” icon in the Header)
- [ ] Change center of map dot from red to a more accessible color also fix movement of dot to reflect Andrew's dot- extra div around map.
